### ISSUE TITLE
Rustfmt

### ISSUE THREAD

**Issue by bddap** [rapodaca/chemcore#3]
Rust has a really nice code formatter. For Rust, [rustfmt](https://github.com/rust-lang/rustfmt) is a defacto-standard. I can highly recommend trying it out.

I'm opening this issue because I'd like to contribute to chemcore in future without needing to worry about formatting. In my experience, its easier to introduce a formatter early on in a projects life to minimize impact on `git-blame`.

In case you are interested, I'll submit a PR that shows what changes rustfmt makes.

<details>
<summary>Note</summary>

Before autoformatting you'll want tag the `Element` enum in `src/molecule/element.rs` with `#[rustfmt::skip]`.
You can autoformat everything with https://github.com/rust-lang/rustfmt#on-the-stable-toolchain.
</details>

**Comment by rapodaca** [comment]
That's a good idea and I'd be happy to take a pull request.

**Comment by rapodaca** [comment]
See #4.
